/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[33] = {10, 6, 0, 5, 10, 15, 20, 22, 24, 0, 1, 7, 8, 9, 0, 1, 7, 8, 9, 0, 1, 7, 8, 9, 0, 1, 7, 8, 9, 0, 1, 0, 1};
static const casadi_int casadi_s5[3] = {6, 0, 0};

/* augmented_yaw_model_constr_h_e_fun_jac_uxt_zt:(i0[10],i1[],i2[],i3[5])->(o0[6],o1[10x6,24nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][9] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][0] : 0;
  a3=arg[0]? arg[0][7] : 0;
  a3=(a2-a3);
  a4=(a1*a3);
  a5=sin(a0);
  a6=arg[0]? arg[0][1] : 0;
  a7=arg[0]? arg[0][8] : 0;
  a7=(a6-a7);
  a8=(a5*a7);
  a4=(a4+a8);
  if (res[0]!=0) res[0][0]=a4;
  a8=cos(a0);
  a9=(a8*a7);
  a10=sin(a0);
  a11=(a10*a3);
  a9=(a9-a11);
  a11=arg[3]? arg[3][0] : 0;
  a12=tan(a11);
  a13=(a4*a12);
  a13=(a9+a13);
  if (res[0]!=0) res[0][1]=a13;
  a11=tan(a11);
  a13=(a4*a11);
  a13=(a13-a9);
  if (res[0]!=0) res[0][2]=a13;
  a13=arg[3]? arg[3][1] : 0;
  a13=(a13-a4);
  if (res[0]!=0) res[0][3]=a13;
  a13=arg[3]? arg[3][4] : 0;
  a4=arg[3]? arg[3][2] : 0;
  a2=(a2-a4);
  a4=casadi_sq(a2);
  a9=arg[3]? arg[3][3] : 0;
  a6=(a6-a9);
  a9=casadi_sq(a6);
  a4=(a4+a9);
  a9=(a13-a4);
  if (res[0]!=0) res[0][4]=a9;
  a4=(a4+a13);
  if (res[0]!=0) res[0][5]=a4;
  if (res[1]!=0) res[1][0]=a1;
  if (res[1]!=0) res[1][1]=a5;
  a4=(-a1);
  if (res[1]!=0) res[1][2]=a4;
  a4=(-a5);
  if (res[1]!=0) res[1][3]=a4;
  a4=cos(a0);
  a4=(a7*a4);
  a13=sin(a0);
  a13=(a3*a13);
  a4=(a4-a13);
  if (res[1]!=0) res[1][4]=a4;
  a13=(a12*a1);
  a13=(a13-a10);
  if (res[1]!=0) res[1][5]=a13;
  a13=(a12*a5);
  a13=(a8+a13);
  if (res[1]!=0) res[1][6]=a13;
  a13=(a12*a1);
  a13=(a10-a13);
  if (res[1]!=0) res[1][7]=a13;
  a13=(a12*a5);
  a13=(a8+a13);
  a13=(-a13);
  if (res[1]!=0) res[1][8]=a13;
  a12=(a12*a4);
  a13=sin(a0);
  a7=(a7*a13);
  a0=cos(a0);
  a3=(a3*a0);
  a7=(a7+a3);
  a12=(a12-a7);
  if (res[1]!=0) res[1][9]=a12;
  a12=(a11*a1);
  a12=(a12+a10);
  if (res[1]!=0) res[1][10]=a12;
  a12=(a11*a5);
  a12=(a12-a8);
  if (res[1]!=0) res[1][11]=a12;
  a12=(a11*a1);
  a12=(a12+a10);
  a12=(-a12);
  if (res[1]!=0) res[1][12]=a12;
  a12=(a11*a5);
  a8=(a8-a12);
  if (res[1]!=0) res[1][13]=a8;
  a11=(a11*a4);
  a11=(a11+a7);
  if (res[1]!=0) res[1][14]=a11;
  a11=(-a1);
  if (res[1]!=0) res[1][15]=a11;
  a11=(-a5);
  if (res[1]!=0) res[1][16]=a11;
  if (res[1]!=0) res[1][17]=a1;
  if (res[1]!=0) res[1][18]=a5;
  a4=(-a4);
  if (res[1]!=0) res[1][19]=a4;
  a2=(a2+a2);
  a4=(-a2);
  if (res[1]!=0) res[1][20]=a4;
  a6=(a6+a6);
  a4=(-a6);
  if (res[1]!=0) res[1][21]=a4;
  if (res[1]!=0) res[1][22]=a2;
  if (res[1]!=0) res[1][23]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int augmented_yaw_model_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int augmented_yaw_model_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
